defmodule BuscaEstagio.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:internships) do
      add :url, :text, null: false
    end

    create unique_index(:internships, [:url], name: "internships_unique_url_index")
  end

  def down do
    drop_if_exists unique_index(:internships, [:url], name: "internships_unique_url_index")

    alter table(:internships) do
      remove :url
    end
  end
end
