defmodule BuscaEstagio.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:internships) do
      add :source, :text, null: false, default: "unknown"
    end
  end

  def down do
    alter table(:internships) do
      remove :source
    end
  end
end
